# Generated by Django 4.1.3 on 2022-12-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_description_alter_ad_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
