# Generated by Django 4.1.3 on 2022-12-04 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_category_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slag',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
